LMS/Controllers/FindingCallNumbersController.cs
using LMS.Models;
using LMS_Management.FindingCallNumbers;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LMS.Controllers
{
    public class FindingCallNumbersController : Controller
    {
        private int TOP_LEVEL = 0;
        private int SECOND_LEVEL = 1;
        private int THIRD_LEVEL = 2;
        private int depth = 3;
        private Tree<Pair> gameTree;
        private static List<Pair>? correctPath;

        public IActionResult Index()
        {
            CreateTreeFile treeFile = new CreateTreeFile();
            

            if (treeFile.FileExists())
            {
                //If the file exists read the tree
                gameTree = treeFile.ReadFile();
            }
            else
            {
                //If the tree data file doesnt exist then create it
                treeFile.CreateFile();
                gameTree = treeFile.ReadFile();
            }

            correctPath = gameTree.GetPathToRandomNode(gameTree.Root, depth);

            var incorrectNodePath1 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            //Check the uniqueness of the paths so that there are no duplicates

            while (incorrectNodePath1[TOP_LEVEL] == correctPath[TOP_LEVEL])
            {
                incorrectNodePath1 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            }

            var incorrectNodePath2 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            while (incorrectNodePath2[TOP_LEVEL] == correctPath[TOP_LEVEL] || incorrectNodePath2[TOP_LEVEL] == incorrectNodePath1[TOP_LEVEL])
            {
                incorrectNodePath2 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            }

            var incorrectNodePath3 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            while (incorrectNodePath3[TOP_LEVEL] == correctPath[TOP_LEVEL] || incorrectNodePath3[TOP_LEVEL] == incorrectNodePath1[TOP_LEVEL] || incorrectNodePath3[TOP_LEVEL] == incorrectNodePath2[TOP_LEVEL])
            {
                incorrectNodePath3 = gameTree.GetPathToRandomNode(gameTree.Root, depth);
            }


            var model = new FindingCallNumbers
            {
                Question = correctPath[THIRD_LEVEL].Description,
                FirstLevel = new List<Pair> { correctPath[TOP_LEVEL], incorrectNodePath1[TOP_LEVEL], incorrectNodePath2[TOP_LEVEL], incorrectNodePath3[TOP_LEVEL] },
                SecondLevel = GetNextLevel(correctPath[TOP_LEVEL]),
                ThirdLevel = GetNextLevel(correctPath[SECOND_LEVEL])
            };

            model.SortLevels();
            

            return View(model);
        }

        private List<Pair> GetNextLevel(Pair node)
        {
            //get the children of the parent node
            var children = gameTree.GetChildren(node);

            if(children.Count <= 4)
            {
                return children;
            }
            else
            {
                //Get 4 random children 
                var randomChildren = children.OrderBy(x => Guid.NewGuid()).Take(4).ToList();
                return randomChildren;
            }
        }

        public IActionResult Check(string selectedOption, string level)
        {
            //The level tells us what level the node is at
            int numLevel = Convert.ToInt32(level);

            if (!string.IsNullOrEmpty(selectedOption))
            {
                //The choice is sent to the controller as a string number:description
                string[] choice = selectedOption.Split(':');
                Pair userPair = new Pair()
                {
                    Number = choice[0],
                    Description = choice[1]
                };

                switch (numLevel)
                {
                    case 0:
                        if (correctPath[TOP_LEVEL].CompareObj(userPair))
                        {
                            return Json(true);
                        }
                        break;
                    case 1:
                        if (correctPath[SECOND_LEVEL].CompareObj(userPair))
                        {
                            return Json(true);
                        }
                        break;
                    case 2:
                        if (correctPath[THIRD_LEVEL].CompareObj(userPair))
                        {
                            return Json(true);
                        }
                        break;
                    default:
                        return Json(false);
                }
            }
          
            return Json(false);
        }

        


    }

}

LMS/Controllers/HomeController.cs
using LMS.Models;
using LMS_Management.IdentifyingAreas;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LMS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Learn()
        {
            return View();
        }

        public IActionResult ComingSoon()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LMS/Controllers/IdentifyingAreasController.cs
using LMS.Models;
using LMS_Management.IdentifyingAreas;
using Microsoft.AspNetCore.Mvc;

namespace LMS.Controllers
{
    public class IdentifyingAreasController : Controller
    {
        private IdentifyingAreas identifyingAreas = new IdentifyingAreas();
        private Dictionary<string, string> levels = new Dictionary<string, string>();
        private static Dictionary<string, string> areas = new Dictionary<string, string>();
        private string mode = "";

        public ActionResult Index()
        {
            levels = identifyingAreas.GameLevelDescription();
            ViewBag.Levels = levels;

            //Check what the game mode is
            mode = HttpContext.Session.GetString("Mode");
            if (string.IsNullOrEmpty(mode))
            {
                mode = "Call Numbers to Description";
                HttpContext.Session.SetString("Mode", mode);
            }

            IdentifyingAreasModel areasModel = new IdentifyingAreasModel();
            areas = identifyingAreas.GenerateAreas(mode);
            areasModel.Areas = areas;
            areasModel.Extras = identifyingAreas.GetExtras();
            areasModel.Mode = mode;

            var keys = areas.Keys.ToList();
            var values = areas.Values.ToList();
            //Suffle the list including the extras
            if (mode == "Call Numbers to Description")
            {
                var shuffledKeys = keys.OrderBy(x => Guid.NewGuid()).ToList();
                areasModel.ShuffledKeys = shuffledKeys;

                values.AddRange(areasModel.Extras);
                var shuffledValues = values.OrderBy(x => Guid.NewGuid()).ToList();
                areasModel.ShuffledValues = shuffledValues;
                return View(areasModel);
            }
            else
            {
                var shuffledValues = values.OrderBy(x => Guid.NewGuid()).ToList();
                areasModel.ShuffledValues = shuffledValues;

                keys.AddRange(areasModel.Extras);
                var shuffledKeys = keys.OrderBy(x => Guid.NewGuid()).ToList();
                areasModel.ShuffledKeys = shuffledKeys;
                return View(areasModel);
            }



        }

        [HttpPost]
        public IActionResult SubmitSortedItems([FromBody] Dictionary<string, string> userAreas)
        {

            var outcome = identifyingAreas.CheckUserDictionary(areas, userAreas);

            var result = "Lose";

            if (outcome)
            {
                result = "Win";
            }
            ChangeMode();
            return Ok(result);
        }

        private void ChangeMode()
        {
            // Update the mode in the session
            mode = HttpContext.Session.GetString("Mode");
            if (mode == "Call Numbers to Description")
            {
                HttpContext.Session.SetString("Mode", "Descriptions to Call Numbers");
            }
            else
            {
                HttpContext.Session.SetString("Mode", "Call Numbers to Description");
            }


        }
    }
}

LMS/Controllers/ReplaceBooksController.cs
using Microsoft.AspNetCore.Mvc;
using LMS_Management.ReplacingBooks;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace LMS.Controllers
{
    public class ReplaceBooksController : Controller
    {
        private ReplacingBooks game = new ReplacingBooks();
        private Dictionary<string, string> levels = new Dictionary<string, string>();
        private static List<string> callNumbers = new List<string>();

        public IActionResult Index()
        {
            callNumbers = game.GenerateCallNumbers();
            ViewBag.Items = callNumbers;

            levels = game.GameLevelDescription();
            ViewBag.Levels = levels;

            return View();
        }

        [HttpPost]
        public IActionResult SubmitSortedItems([FromBody] string[] sortedItems)
        {
            //convert the array to a list
            var items = sortedItems.ToList();

            //When the list is retrieved it has some extra characters so we need to remove them
            List<string> extractedNumbers = sortedItems
            .Select(item =>
            {
                // Match numbers (with optional period and exactly 2 digits after the period) followed by 3 letters
                MatchCollection matches = Regex.Matches(item, @"\d+(\.\d{2})? [A-Z]{3}");

                // Join the matched numbers into a single string
                return string.Join(" ", matches.Cast<Match>().Select(match => match.Value));
            })
            .ToList();

            //check the order of the items
            var outcome = game.CheckOrder(extractedNumbers, callNumbers);

            var result = "Lose";

            if (outcome)
            {
                result = "Win";
            }


            return Ok(result);
        }

    }
}

LMS/Views/Home/ComingSoon.cshtml
@{
    ViewData["Title"] = "Coming Soon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="page-headings">Coming Soon!!!</h1>

LMS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <link rel="stylesheet" href="~/css/landingPagesStyles.css" asp-append-version="true" />
</head>

<body>
    <div class="card mb-2" id="landing-container">
        <div class="row g-0">
            <div class="col-lg-7 col-md-7" id="large-screen-img1" style="display:none;">
                <img src="~/images/stack-of-books.png" class="landing-img img-fluid rounded-start" alt="stack of books">
            </div>
            <div class="col-lg-5 col-md-5">
                <div class="card-body" id="landing-body">
                    <h1 class="landing-heading text-white">Master Dewey,</h1>
                    <h1 class="landing-heading text-white">the Fun Way!</h1> 
                    <a asp-controller="Home" asp-action="Learn">
                        <input type="submit" value="Start" class="landing-btn" style="width:12.5rem;" />
                    </a>
                </div>
            </div>

            <div class="col-lg-7 col-md-7" id="large-screen-img2">
                <img src="~/images/stack-of-books.png" class="landing-img img-fluid rounded-start" alt="stack of books">
            </div>
        </div>
    </div>
</body>

LMS/Views/Home/Learn.cshtml
@{
    ViewData["Title"] = "Learn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center selection-row">

    <div class="row row-cols-1 row-cols-md-3 g-4 ">
        <div class="col">
            <a asp-controller="ReplaceBooks" asp-action="Index" style="text-decoration: none;">
                <div class="card h-100 learn-cards" id="replacing-books-square">
                    <img src="~/images/book.png" class="card-img-top square-img" alt="...">
                    <div class="card-body">
                        <h5 class="text-white square-text">Replacing Books</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col">
            <a asp-controller="IdentifyingAreas" asp-action="Index" style="text-decoration: none;">
                <div class="card h-100 learn-cards" id="identifying-areas-square">
                    <img src="~/images/search.png" class="card-img-top square-img" alt="...">
                    <div class="card-body">
                        <h5 class="text-white square-text">Identifying Areas</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="col">
            <a asp-controller="FindingCallNumbers" asp-action="Index" style="text-decoration: none;">
                <div class="card h-100 learn-cards" id="find-callnums-square">
                    <img src="~/images/lamp.png" class="card-img-top square-img" alt="...">
                    <div class="card-body">
                        <h5 class="text-white square-text">
                            Finding Call
                            Numbers
                        </h5>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>